dataset:
  name: "anet"
  num_classes: 200
  training:
    video_info_path: "./data/activitynet_annotations/video_info_new.csv"
    video_info_path_unlabeled: "./data/activitynet_annotations/"
    video_anno_path: "./data/activitynet_annotations/anet_anno_action.json"
    num_frame: 16
    output_path: '/root/models/SPOT/output/'
    unlabel_percent: 0.7
    use_semi: True
    
  testing:
    video_info_path: "./data/activitynet_annotations/video_info_new.csv"
    video_info_path_unlabeled: "./data/activitynet_annotations/"
    video_anno_path: "./data/activitynet_annotations/anet_anno_action.json"
    num_frame: 16
    output_path: '/root/models/SPOT/output/'
    unlabel_percent: 0.7 # Never used
    use_semi: True

model:
  embedding_head: 4
  feat_dim: 400
  temporal_scale: 100

pretraining:
  warmup_epoch: 30 # Default 30
  consecutive_warmup_epochs: 3 # 3 works well

training:
  batch_size: 25 # 100, 50, 25 make it run, but 100 crashes (CUDA out of memory on 80GB A100), 1 seems to work for training but not pretraining 
  learning_rate: 0.0004
  weight_decay: 0.005
  alternate: True
  max_epoch: 40 # 40 works well
  consecutive_train_epochs: 3 # 3 works well
  checkpoint_path: "/root/models/SPOT/output/"
  random_seed: 1
  step: 10
  gamma: 0.2
  feature_path: "/data/i5O/ActivityNet1.3/train/"
  num_gpu: 1 

loss:
  lambda_1: 0.5
  lambda_2: 0.4

testing:
  feature_path: "/data/i5O/ActivityNet1.3/test/"
  cls_thresh: 0.01
  mask_thresh: [0,0.2,0.4,0.6,0.8]
  class_thresh: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
  top_k_snip: 10
  top_k: 500
  nms_thresh: 0.6
