dataset:
  name: "thumos"
  num_classes: 21
  training:
    video_info_path: "data/thumos_annotations/val_video_info.csv" # from AFSD. TODO: we are using the validation set for training? Not something like the actionformer subset?
    video_info_path_unlabeled: "./data/activitynet_annotations/"
    video_anno_path: "data/thumos_annotations/val_Annotation_ours.csv" # from AFSD 
    num_frame: 16
    output_path: '/root/models/SPOT/thumos_output/'
    unlabel_percent: 0.9
    use_semi: True
    clip_length: 256 # from AFSD
    clip_stride: 30 # from AFSD
    crop_size: 96 # from AFSD
    class_info: "./data/thumos_annotations/Class Index_Detection.txt"
    
  testing:
    video_info_path: "data/thumos_annotations/test_video_info.csv" # from AFSD 
    video_info_path_unlabeled: "./data/activitynet_annotations/"
    video_anno_path: "./data/activitynet_annotations/anet_anno_action.json"
    num_frame: 16
    output_path: '/root/models/SPOT/thumos_output/'
    unlabel_percent: 0.9
    use_semi: True
    crop_size: 96 # for AFSD
    clip_length: 256 # for AFSD
    clip_stride: 128 # for AFSD

model:
  embedding_head: 4
  feat_dim: 400
  temporal_scale: 100

training:
  batch_size: 100
  learning_rate: 0.0004
  weight_decay: 0.005
  max_epoch: 25
  checkpoint_path: "/root/models/SPOT/thumos_output/"
  random_seed: 1
  step: 10
  gamma: 0.2
  feature_path: #TODO: add the path to the features to be used; corresponds to video_data_path
  num_gpu: 1
  feature_path: "/data/i5O/THUMOS14/I3D_fromSPOTrepo/train/" 

loss:
  lambda_1: 0.5
  lambda_2: 0.4

testing:
  feature_path: #TODO: add the path to the features to be used; corresponds to video_data_path
  cls_thresh: 0.01
  mask_thresh: [0,0.2,0.4,0.6,0.8]
  class_thresh: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
  top_k_snip: 10
  top_k: 500
  nms_thresh: 0.6
  feature_path: "/data/i5O/THUMOS14/I3D_fromSPOTrepo/test/"
